# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-03 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0033_auto_20190303_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='payment_made',
            field=models.BooleanField(default=False, verbose_name='Payment Made'),
        ),
    ]
